# Generated by Django 5.0.2 on 2024-04-02 21:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_fallowers_alter_post_created_at'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Fallowers',
            new_name='FallowersCount',
        ),
        migrations.AlterField(
            model_name='post',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 4, 3, 0, 5, 47, 192802)),
        ),
    ]
